### ISSUE TITLE
Create Initial Mock

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#10]
**Goal**
Create a mock of what the MVP will look like.

**Tasks**
- [ ] Make a simple mock of the project
- [ ] We need a sidebar and topbar
- [ ] A simple gallery view page (photos only, no videos)
- [ ] (Login/Register Pages?)

**Comment by tsuukii** [comment]
View [Figma File](https://www.figma.com/proto/ylGLDdQP5JAtWz9Wldmmi6/Galleme?node-id=2%3A3&scaling=min-zoom&page-id=0%3A1)

![Screenshot 2021-09-04 at 13 26 16](https://user-images.githubusercontent.com/30908158/132092804-e00e1558-6e54-435a-944d-bf1e4a6d007a.png)
