### ISSUE TITLE
Setup Storybook components and file structure

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#11]
**Goal**
Currently are folders are messed up by default `ionic` and `storybook` components. We want to clean this up and add our own boilerplate.

**Tasks** 
- [x] Remove default Ionic components
- [x] Remove Storybook components
- [x] Introduce our own file structure
