### ISSUE TITLE
Make a `ButtonWithIcon` component

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#15]
**Goal**
Extend our current button component (#14) allowing us to create buttons with icons inside.

**Context**
Make a new component called `ButtonWithIcon`. This component will have a `BaseButton` inside with a customized slot for an icon and text. The props of this new component will then take in an Icon and the text. The other props of the normal `BaseButton` should still be passed over the new `ButtonWithIcon`.

**Tasks**

- [x] Create the new `ButtonWithIcon`
- [x] Extend the `BaseButton`
- [x] Allow for use of one Icon and text
- [x] Write new stories for the component
