### ISSUE TITLE
Introduce `Faker.js` and other packages into the project

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#16]
**Goal**
Add `Faker.js` to the project and configure an example for it. We also need an SVG loader for Icons.

**Context**
`Faker.js` lets us easily create mock data for our stories. It will be helpful to have it setup.

**Tasks**

- [ ] Install `Faker.js`
- [ ] Incoperate it into a example story
- [ ] Add a SVG component loader into the project for icons
