### ISSUE TITLE
Develop design kit

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#24]
**Goal**
We need to decide what colors and spacings we will be using.

**Context**
In order to customize this for the frontend we can use the [TailwindCSS Config](https://tailwindcss.com/docs/configuration).

**Tasks**

- [ ] Develop a set of brand colors and make sure everyone is okay with them
- [ ] Add the branding colors to the tailwindcss file
- [ ] Take care of any other project variables we want to set in the config file.

**Comment by tsuukii** [comment]
blocked by #10
