### ISSUE TITLE
Create `Card` component

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#26]
**Goal**
We want to have a simple card component we can reuse in our project.

**Tasks**

- [ ] Create a card component
- [ ] Pass the props, `title` and `theme`
- [ ] Allow for the use of 2 slots. The Main content (can just be the defaut slot) and a header slot (in case we want to add a right aligned button for example)
- [ ] Create stories for both
