### ISSUE TITLE
Updated CI to include `build`

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#27]
**Goal**
We need to extend our CI.

**Tasks**

- [ ] Add Build step
- [ ] Extend Lint step (#22)
- [ ] Clean up CI pipeline
