### ISSUE TITLE
Implement `Auth Store`

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#35]
**Goal**
We need a `VueX` store to house the information about the current user.

**Context**
For the start this does not have to be very complicated. We just need a simple user store, that we can easily expand with more information once it is included in the backend.

**Tasks**

- [ ] Create a new `auth` store
- [ ] Create a user object that we can easily expand later. 
- [ ] Write some simple mutations that we can use to modify the store
- [ ] Write a demo user (use `Faker` for this.)
