### ISSUE TITLE
Create `Navbar` component

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#36]
**Goal**
We want to create a temporary navbar, that we can use as a base and customize in the future.

**Tasks**

- [ ] Make a new navbar component
- [ ] Have a logo (or text) be on the left side, while multiple links can be added on the right side. 
- [ ] Create stories for the navbar

**Extra**

- [ ] Make sure the Navbar works on mobile devices
- [ ] Add a slide over panel for mobile devices (my advice is to bind the `open` property to the `data()` generator. This can be done within the component.
