### ISSUE TITLE
Create `alert` component

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#38]
**Goal**
Create a simple top alert component.

**Tasks**

- [x] Create the alert component
- [x] Add multiple color schemes
- [x] Write stories for the alerts
