### ISSUE TITLE
Write StoryBook guide

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#7]
**Goal**
Write a short and simple documentation about what storybook is, why we use it and how to use it.

**Context**
Not everyone has used Storybook and we want to provide the needed documention to help them.

**Tasks**
- [x] Write an introduction about what storybook is
- [x] Explain how to use it
- [x] Write a demo story to use as an example
- [x] (Link helpful resouces)
