### ISSUE TITLE
Create a simple button component

### ISSUE THREAD

**Issue by tsuukii** [Galleme/frontend#9]
**Goal**
Create a simple button that we can resuse in our project.

**Context**
We need a simple well designed button that we can use anywhere we want.

**Tasks**
- [x] Create the button component
- [x] The button should have 3 sizes (sm, md, lg)
- [x] There should be 3-4 color schemes `primary, secondary, danger, success`. Use Tailwind [`@apply`](https://tailwindcss.com/docs/extracting-components#extracting-component-classes-with-apply) to make custom css classes. 
- [x] There should be a prop to disable the button
- [x] The button should `emit` the onClick event as a function. 

**Mock**
![Screenshot 2021-09-03 at 17 37 04](https://user-images.githubusercontent.com/30908158/132031507-01665656-6f32-41d7-8abe-fe2a3410e31a.png)
